#version: '3.4'

services:
  # Service pour la base de données PostgreSQL
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service pour l'API FastAPI
  api:
    build: . 
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - APP_DB_HOST=db
      - APP_DB_USER=postgres
      - APP_DB_PASS=password
      - APP_DB_NAME=library_db
      - APP_JWT_SECRET_KEY=secret
    depends_on:
      - db
    restart: always
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health"] 
      interval: 10s
      timeout: 5s
      retries: 5

# Volumes nommés pour la persistance des données
volumes:
  postgres_data: